### ISSUE TITLE
Value error appears in graph classification task with MUTAG 

### ISSUE THREAD

**Issue by 7qchen** [SwiftieH/IGNN#4]
Hi, thank you for your code, I've learned a lot from it. 
Now I met a problem("ValueError: row, column, and data arrays must be 1-D") when I'm running train_IGNN.py in your graphclassification folder. The problem occurs because data.edge_attr is not None and it's a N*4 tensor, so adj_sp cannot be constructed correctly. Could you please tell me how to fix this?

Thank you and look forward to your reply:)

**Comment by SwiftieH** [comment]
Hi,

For MUTAG, the edge attribute is the corresponding edge label, which can be referred [here](https://chrsmrrs.github.io/datasets/docs/datasets/). I quote it here for your reference:

```
Edge labels:
  0  aromatic
  1  single
  2  double
  3  triple
```
Thus you can direct take the indices of the N*4 tensor as the labels for edges, and use it to construct your adjacency: 

`edge_weight = data.edge_attr.argmax(1)`

Actually you can also ignore the edge attribute by treating it as unweighted graphs, as the examples provided in [pyg](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/mutag_gin.py).

I hope this answers your question.

**Comment by 7qchen** [comment]
Thank you so much for your answer. It helps me a lot:) BTW, could you please tell me that do you use the edge labels or just ignore them in your node classification experiments?

**Comment by SwiftieH** [comment]
No problem :) We just ignore them and use the graphs as unweighted ones in experiments.
